export const egyptCities = [
  { value: "cairo", label: "Cairo " },
  { value: "giza", label: "Giza " },
  { value: "alexandria", label: "Alexandria " },
  { value: "qalyubia", label: "Qalyubia " },
  { value: "dakahlia", label: "Dakahlia " },
  { value: "sharqia", label: "Sharqia " },
  { value: "gharbia", label: "Gharbia " },
  { value: "monufia", label: "Monufia " },
  { value: "beheira", label: "Beheira " },
  { value: "damietta", label: "Damietta " },
  { value: "port-said", label: "Port Said " },
  { value: "ismailia", label: "Ismailia " },
  { value: "suez", label: "Suez " },
  { value: "kafr-el-sheikh", label: "Kafr El-Sheikh " },
  { value: "fayoum", label: "Fayoum " },
  { value: "beni-suef", label: "Beni Suef " },
  { value: "minya", label: "Minya " },
  { value: "assiut", label: "Assiut " },
  { value: "sohag", label: "Sohag " },
  { value: "qena", label: "Qena " },
  { value: "luxor", label: "Luxor " },
  { value: "aswan", label: "Aswan " },
  { value: "red-sea", label: "Red Sea " },
  { value: "new-valley", label: "New Valley " },
  { value: "matrouh", label: "Matrouh " },
  { value: "north-sinai", label: "North Sinai " },
  { value: "south-sinai", label: "South Sinai " }
];